---
name: CI

on:
  pull_request:
    branches: {{ cookiecutter.project_branch }}
jobs:
  build-and-test:
    name: Build and test
    runs-on: {{ cookiecutter.project_runner }}
    container: elixir:{{ cookiecutter.elixir_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          apk add --update bash openssl git
          mix local.hex --force && mix local.rebar --force
      - name: Install elixir dependencies
        run: mix deps.get
      - name: Run CI Tests
        env:
          MIX_ENV: test
        run: mix ci
